### ISSUE TITLE
TypeError: cr.plugins_.xdkads is undefined

### ISSUE THREAD

**Issue by paganeo** [intel/contruct2plugins#2]
Javascript error!
TypeError: cr.plugins_.xdkads is undefined
http://localhost:50000/data.js, line 1246 (col 4)

This is likely a bug in Construct 2 or a third party plugin or behavior - please report it to the developer. Subsequent errors will be logged to the console.

**Comment by imaffett** [comment]
Hi @paganeo 

Ashley at Scirra has added a better version of the plugin into the 181 release.  Please use that.

**Comment by paganeo** [comment]
Thank you.
